<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'ISC\\Pro\\Admin\\Image_Sources_Columns' => $baseDir . '/admin/includes/image-source-columns.php',
    'ISC\\Pro\\Admin\\Image_Sources_Form_Column' => $baseDir . '/admin/includes/image-sources-form-column.php',
    'ISC\\Pro\\Admin\\Image_Sources_Preview_Column' => $baseDir . '/admin/includes/image-sources-preview-column.php',
    'ISC\\Pro\\Admin\\License' => $baseDir . '/admin/includes/license.php',
    'ISC\\Pro\\Caption' => $baseDir . '/public/caption.php',
    'ISC\\Pro\\Compatibility\\Avada_Builder' => $baseDir . '/includes/compatibility/Avada_Builder.php',
    'ISC\\Pro\\Compatibility\\Divi' => $baseDir . '/includes/compatibility/Divi.php',
    'ISC\\Pro\\Compatibility\\Elementor' => $baseDir . '/includes/compatibility/Elementor.php',
    'ISC\\Pro\\Compatibility\\Gallery_Block_Lightbox' => $baseDir . '/includes/compatibility/Gallery_Block_Lightbox.php',
    'ISC\\Pro\\Compatibility\\Jet_Engine' => $baseDir . '/includes/compatibility/Jet_Engine.php',
    'ISC\\Pro\\Compatibility\\Kadence' => $baseDir . '/includes/compatibility/Kadence.php',
    'ISC\\Pro\\Compatibility\\WPML' => $baseDir . '/includes/compatibility/WPML.php',
    'ISC\\Pro\\Compatibility\\WP_Bakery' => $baseDir . '/includes/compatibility/WP_Bakery.php',
    'ISC\\Pro\\Custom_Attribute_Processor' => $baseDir . '/includes/Custom_Attribute_Processor.php',
    'ISC\\Pro\\IPTC' => $baseDir . '/includes/IPTC.php',
    'ISC\\Pro\\Indexer\\Index_Run' => $baseDir . '/includes/indexer/admin/index-run.php',
    'ISC\\Pro\\Indexer\\Index_Table' => $baseDir . '/includes/indexer/index-table.php',
    'ISC\\Pro\\Indexer\\Indexer' => $baseDir . '/includes/indexer/indexer.php',
    'ISC\\Pro\\Indexer\\Indexer_Admin' => $baseDir . '/includes/indexer/admin/indexer-admin.php',
    'ISC\\Pro\\Indexer\\Indexer_Public' => $baseDir . '/includes/indexer/public/indexer-public.php',
    'ISC\\Pro\\List_Layout_Details' => $baseDir . '/includes/List_Layout_Details.php',
    'ISC\\Pro\\Unused_Images' => $baseDir . '/includes/unused-images/admin/unused-images.php',
    'ISC\\Pro\\Unused_Images\\Admin\\Appearances_Column' => $baseDir . '/includes/unused-images/admin/appearances-column.php',
    'ISC\\Pro\\Unused_Images\\Admin\\Appearances_List' => $baseDir . '/includes/unused-images/admin/appearance-list.php',
    'ISC\\Pro\\Unused_Images\\Database_Check_Model' => $baseDir . '/includes/unused-images/database-check-model.php',
    'ISC\\Pro\\Unused_Images_List_Table' => $baseDir . '/includes/unused-images/admin/list-table.php',
    'ISC\\Pro\\WP_Caption' => $baseDir . '/includes/wp-caption.php',
    'ISC\\Settings\\Sections\\Unused_Images' => $baseDir . '/includes/unused-images/admin/settings.php',
    'ISC_Pro_Admin' => $baseDir . '/admin/admin.php',
    'ISC_Pro_Admin_Storage_Form' => $baseDir . '/admin/includes/storage-form.php',
    'ISC_Pro_Model' => $baseDir . '/includes/model.php',
    'ISC_Pro_Public' => $baseDir . '/public/public.php',
    'ISC_SL_Plugin_Updater' => $baseDir . '/admin/includes/ISC_SL_Plugin_Updater.php',
);
