<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2610dbd1e58f45f21033b41429b8281f
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'ISC\\Pro\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ISC\\Pro\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'ISC\\Pro\\Admin\\Image_Sources_Columns' => __DIR__ . '/../..' . '/admin/includes/image-source-columns.php',
        'ISC\\Pro\\Admin\\Image_Sources_Form_Column' => __DIR__ . '/../..' . '/admin/includes/image-sources-form-column.php',
        'ISC\\Pro\\Admin\\Image_Sources_Preview_Column' => __DIR__ . '/../..' . '/admin/includes/image-sources-preview-column.php',
        'ISC\\Pro\\Admin\\License' => __DIR__ . '/../..' . '/admin/includes/license.php',
        'ISC\\Pro\\Caption' => __DIR__ . '/../..' . '/public/caption.php',
        'ISC\\Pro\\Compatibility\\Avada_Builder' => __DIR__ . '/../..' . '/includes/compatibility/Avada_Builder.php',
        'ISC\\Pro\\Compatibility\\Divi' => __DIR__ . '/../..' . '/includes/compatibility/Divi.php',
        'ISC\\Pro\\Compatibility\\Elementor' => __DIR__ . '/../..' . '/includes/compatibility/Elementor.php',
        'ISC\\Pro\\Compatibility\\Gallery_Block_Lightbox' => __DIR__ . '/../..' . '/includes/compatibility/Gallery_Block_Lightbox.php',
        'ISC\\Pro\\Compatibility\\Jet_Engine' => __DIR__ . '/../..' . '/includes/compatibility/Jet_Engine.php',
        'ISC\\Pro\\Compatibility\\Kadence' => __DIR__ . '/../..' . '/includes/compatibility/Kadence.php',
        'ISC\\Pro\\Compatibility\\WPML' => __DIR__ . '/../..' . '/includes/compatibility/WPML.php',
        'ISC\\Pro\\Compatibility\\WP_Bakery' => __DIR__ . '/../..' . '/includes/compatibility/WP_Bakery.php',
        'ISC\\Pro\\Custom_Attribute_Processor' => __DIR__ . '/../..' . '/includes/Custom_Attribute_Processor.php',
        'ISC\\Pro\\IPTC' => __DIR__ . '/../..' . '/includes/IPTC.php',
        'ISC\\Pro\\Indexer\\Index_Run' => __DIR__ . '/../..' . '/includes/indexer/admin/index-run.php',
        'ISC\\Pro\\Indexer\\Index_Table' => __DIR__ . '/../..' . '/includes/indexer/index-table.php',
        'ISC\\Pro\\Indexer\\Indexer' => __DIR__ . '/../..' . '/includes/indexer/indexer.php',
        'ISC\\Pro\\Indexer\\Indexer_Admin' => __DIR__ . '/../..' . '/includes/indexer/admin/indexer-admin.php',
        'ISC\\Pro\\Indexer\\Indexer_Public' => __DIR__ . '/../..' . '/includes/indexer/public/indexer-public.php',
        'ISC\\Pro\\List_Layout_Details' => __DIR__ . '/../..' . '/includes/List_Layout_Details.php',
        'ISC\\Pro\\Unused_Images' => __DIR__ . '/../..' . '/includes/unused-images/admin/unused-images.php',
        'ISC\\Pro\\Unused_Images\\Admin\\Appearances_Column' => __DIR__ . '/../..' . '/includes/unused-images/admin/appearances-column.php',
        'ISC\\Pro\\Unused_Images\\Admin\\Appearances_List' => __DIR__ . '/../..' . '/includes/unused-images/admin/appearance-list.php',
        'ISC\\Pro\\Unused_Images\\Database_Check_Model' => __DIR__ . '/../..' . '/includes/unused-images/database-check-model.php',
        'ISC\\Pro\\Unused_Images_List_Table' => __DIR__ . '/../..' . '/includes/unused-images/admin/list-table.php',
        'ISC\\Pro\\WP_Caption' => __DIR__ . '/../..' . '/includes/wp-caption.php',
        'ISC\\Settings\\Sections\\Unused_Images' => __DIR__ . '/../..' . '/includes/unused-images/admin/settings.php',
        'ISC_Pro_Admin' => __DIR__ . '/../..' . '/admin/admin.php',
        'ISC_Pro_Admin_Storage_Form' => __DIR__ . '/../..' . '/admin/includes/storage-form.php',
        'ISC_Pro_Model' => __DIR__ . '/../..' . '/includes/model.php',
        'ISC_Pro_Public' => __DIR__ . '/../..' . '/public/public.php',
        'ISC_SL_Plugin_Updater' => __DIR__ . '/../..' . '/admin/includes/ISC_SL_Plugin_Updater.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2610dbd1e58f45f21033b41429b8281f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2610dbd1e58f45f21033b41429b8281f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit2610dbd1e58f45f21033b41429b8281f::$classMap;

        }, null, ClassLoader::class);
    }
}
